{% set name = "kjobwidgets" %}
{% set version = "5.68.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kjobwidgets-{{ version }}.tar.xz
  sha256: a11ba51ed0ab330f9a921cf0a61e604c27d88c1c2ea477a875bc0a0cd228a292

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kjobwidgets', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt
    - kcoreaddons
    - kwidgetsaddons

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5JobWidgets.so

about:
  home: https://api.kde.org/frameworks/kjobwidgets/html/index.html
  license: LGPL-v2.1-or-later
  license_family: GPL
  license_file: COPYING.LIB
  summary: Widgets for showing progress of asynchronous jobs
  description: |
    KJobWIdgets provides widgets for showing progress of asynchronous jobs.
  dev_url: https://cgit.kde.org/kjobwidgets.git/tree

extra:
  recipe-maintainers:
    - scopatz
